In [1]:
#importing numpy package
import numpy as np

In [2]:
#Creating numpy array by using array();
value=45;
numpy_value=np.array(value)


In [3]:
numpy_value

array(45)

In [6]:
type(numpy_value)

numpy.ndarray

In [7]:
numpy_value.ndim

0

In [16]:
#Creating the numpy array with group of values
numpy_values1=np.array([10,20,30,40,50,60])
numpy_values1

array([10, 20, 30, 40, 50, 60])

In [17]:
numpy_values.ndim

1

In [34]:
#Creating numpy array with  nested list or Creating a matrix
numpy_values2=np.array([[10,20,30,40],[50,60,70,80]]); # It is called as matrix
numpy_values2

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [20]:
numpy_values2.ndim

2

In [35]:
#Creating numpy array with multiple nested list or Creating a matrix
numpy_values3=np.array([[10,20,30],[40,50,60],[70,80,90]]); # It is called as matrix
numpy_values3

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [23]:
numpy_values3.ndim

2

Indexing


In [25]:
#We can access numpy array values by using indexing
numpy_values1

array([10, 20, 30, 40, 50, 60])

In [26]:
numpy_values1[0] #Indexing always starts zero

np.int64(10)

In [27]:
numpy_values1[1]

np.int64(20)

In [28]:
numpy_values1[4]

np.int64(50)

In [29]:
numpy_values2 

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [30]:
numpy_values2[0][0] # We can access matrix values by using row and column indexing 

np.int64(10)

In [32]:
numpy_values2[0][3]

np.int64(40)

In [33]:
numpy_values2[1][2]

np.int64(70)

Slicing

In [36]:
numpy_values1

array([10, 20, 30, 40, 50, 60])

In [38]:
numpy_values1[2:3] # We can access numpy values by using slicing also

array([30])

In [40]:
numpy_values1[:]  # Accessing entire numpy array

array([10, 20, 30, 40, 50, 60])

In [42]:
numpy_values1[::-1] # Reverse the numpy array 

array([60, 50, 40, 30, 20, 10])